### ISSUE TITLE
Error: '' does not exist in current working directory when useSubset = TRUE

### ISSUE THREAD

**Issue by ablack3** [ohdsi-studies/Covid19CharacterizationCharybdis#39] opened 2020-06-15 17:44 UTC
When running `Covid19CharacterizationCharybdis::runCohortDiagnostics()` on Windows 10 I got the error `Error: '' does not exist in current working directory`

I think this might caused by a bug in the `getPathToResource` function. which produces paths with double forward slashes. This might not be the cause though since the double forward slash does not cause an error when USE_SUBSET is FALSE. 

``` r

readCsv <- function(resourceFile) {
  packageName <- "Covid19CharacterizationCharybdis"
  pathToCsv <- system.file(resourceFile, package = packageName)
  print(paste("pathToCsv:", ifelse(pathToCsv == "", "<empty string>", pathToCsv)))
  fileContents <- readr::read_csv(pathToCsv, col_types = readr::cols())
  return(fileContents)
}

getPathToResource <- function(useSubset = Sys.getenv("USE_SUBSET")) {
  path <- "settings/"
  useSubset <- as.logical(useSubset)
  if (is.na(useSubset)) {
    useSubset = FALSE
  }
  if (useSubset) {
    path <- file.path(path, "subset/")
  }
  print(paste("path:", path))
  return(path)
}

getCohortGroupsForDiagnostics <- function () {
  resourceFile <- file.path(getPathToResource(), "CohortGroupsDiagnostics.csv")
  print(paste("resourceFile:", resourceFile))
  return(readCsv(resourceFile))
}


Sys.setenv(USE_SUBSET = "TRUE")
getCohortGroupsForDiagnostics()
#> [1] "path: settings//subset"
#> [1] "resourceFile: settings//subset/CohortGroupsDiagnostics.csv"
#> [1] "pathToCsv: <empty string>"
#> Error: '' does not exist in current working directory 

Sys.setenv(USE_SUBSET = "FALSE")
getCohortGroupsForDiagnostics()
#> [1] "path: settings/"
#> [1] "resourceFile: settings//CohortGroupsDiagnostics.csv"
#> [1] "pathToCsv: C:/Users/.../Documents/R/win-library/4.0/Covid19CharacterizationCharybdis/settings//CohortGroupsDiagnostics.csv"
#> # A tibble: 4 x 3
#>   cohortGroup fileName                                          userCanSelect
#>   <chr>       <chr>                                             <lgl>        
#> 1 covid       settings/diagnostics/CohortsToCreateCovid.csv     TRUE         
#> 2 influenza   settings/diagnostics/CohortsToCreateInfluenza.csv TRUE         
#> 3 strata      settings/diagnostics/CohortsToCreateStrata.csv    FALSE        
#> 4 feature     settings/diagnostics/CohortsToCreateFeature.csv   FALSE
```

<sup>Created on 2020-06-15 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

It is unfortunate that `system.file()` returns an empty string if the file does not exist. I'm wondering why OHDSI packages tend to load data using `system.file()` instead of just utilizing internal package data mechanism that the R package insfrastructure provides. http://r-pkgs.had.co.nz/data.html#data-sysdata

**Comment by anthonysena** [comment] 2020-06-15 21:21
@ablack3 - thanks for reporting this and for using the reprex package (very cool!).

I pushed a fix that should address this which closed out the issue. I am re-opening it to see if you could confirm that the issue is closed on your side now?

I revised the `getPathToResource` definition to remove the training '/' which should address the issue. Furthermore, I also added the `mustWork=TRUE` parameter where I'm using `system.file` as that seems to provide a better error when the resource is not found vs. the `Error: '' does not exist in current working directory`.

> I'm wondering why OHDSI packages tend to load data using system.file() instead of just utilizing internal package data mechanism that the R package insfrastructure provides. http://r-pkgs.had.co.nz/data.html#data-sysdata

I'm guessing here a bit so tagging @schuemie so that he can correct me if I am off base. I think the idea with using `system.file` for the settings is that it allows us to keep the settings in a human-readable format. If we opted to use the sysdata approach, I think that makes review a bit harder since you don't know exactly how the data in the resulting `sysdata.rda` was generated. Per that link you mentioned, it also explains: `Again, to make this data reproducible it’s a good idea to include the code used to generate it. Put it in data-raw/.` So the sysdata approach would require double work (code + data) in a way whereas the `system.file` approach allows for a single source of truth in the .csv setting file. That said, it sure would be nice not to have to worry about paths when reading settings :-)

**Comment by ablack3** [comment] 2020-06-16 20:04
Thanks for the fix! Yes I think using `mustWork = T` in `system.file` is a good idea. If the file doesn't exist there is not point in continuing execution. So I think you need to change the name of the file 

`settings/subset/CohortGroups.csv`
to 
`settings/subset/CohortGroupDiagnostics.csv`

``` r
system.file("settings/CohortGroupsDiagnostics.csv", package = "Covid19CharacterizationCharybdis", mustWork = T)
#> [1] "C:/Users/.../Documents/R/win-library/4.0/Covid19CharacterizationCharybdis/settings/CohortGroupsDiagnostics.csv"

system.file("settings/subset/CohortGroupsDiagnostics.csv", package = "Covid19CharacterizationCharybdis", mustWork = T)
#> Error in system.file("settings/subset/CohortGroupsDiagnostics.csv", package = "Covid19CharacterizationCharybdis", : no file found

system.file("settings/subset/CohortGroups.csv", package = "Covid19CharacterizationCharybdis", mustWork = T)
#> [1] "C:/Users/.../Documents/R/win-library/4.0/Covid19CharacterizationCharybdis/settings/subset/CohortGroups.csv"
```

<sup>Created on 2020-06-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by anthonysena** [comment] 2020-06-16 20:50
Thanks @ablack3 - good catch. I'll add that settings file to the subset subfolder and we should be set!

**Comment by anthonysena** [comment] 2020-06-16 22:41
Closing this via https://github.com/ohdsi-studies/Covid19CharacterizationCharybdis/commit/09c4a947e4dbfbd5dd95cf96bd20a1a8653f2a20

**Closed as completed by anthonysena** 2020-06-16 22:41 UTC
