### ISSUE TITLE
Commit 7907813 strata .json files, "invalid UTF-8 input in readChar()"

### ISSUE THREAD

**Issue by jatjasonthomas** [ohdsi-studies/Covid19CharacterizationCharybdis#84] opened 2021-07-11 18:03 UTC
@anthonysena 

**Issue:** Commit 7907813 led to the following error code when I ran the current version of the package: `"Error in readChar(pathToJson, file.info(pathToJson)$size) :    invalid UTF-8 input in readChar()`

The error only happened when creating strata cohorts right at the beginning of attempting to make them but none of the other cohorts threw the error. I'm not sure which strata cohort(s) was/were the problem, however. I do see in my "Covid19CharacterizationCharybdis.txt" file that the first strata cohort created is "Instantiation cohort Prevalent Type 2 Diabetes Mellitus (100.sql)" so perhaps that is the or one of the files at issue. Maybe all the strata .json files are loaded together though and if any of them have an issue the error is thrown.

**Solution:** I replaced the .json files from this commit with the .json files from commit ae5537d. The error went away and the strata cohorts were successfully created.

I know this package is no longer supported but this issue may be worth looking into if whatever caused this problem in commit 7907813 is a process used in the future which might re-create this issue in future packages.

**Comment by anthonysena** [comment] 2021-07-12 13:44
Thanks @jatjasonthomas for reporting this issue. 

Just wanted to confirm: have you rebuilt the package after pulling down the latest code? I was helping someone recently (with a different package) and they encountered the same problem with `readChar` and it was fixed by rebuilding the package which copied in all of the proper resource files, etc.

Thanks!

**Comment by alabarga** [comment] 2021-07-27 14:27
I'm experiencing the same problem using the release 1.4.2

**Comment by anthonysena** [comment] 2021-07-28 15:56
Hi,

I'm having a bit of a challenge reproducing this problem so I'll need some assistance. Here is some code I'm hoping one of you can run to help identify the file(s) exhibiting the problem you are experiencing:

```r
print(sessionInfo())
pathToJson <- file.path(getwd(), "inst/cohorts/")
lfilesJson <-
  dir(
    path = pathToJson,
    pattern = "\\.json$",
    full.names = TRUE,
    recursive = TRUE
  )

for (file in lfilesJson)  {
  tryCatch({
    fileContents <- ""
    fileContents <- readChar(file, file.info(file)$size)
  },
  error = function(e) {
    print(paste0("Problem File: ", file))
  })
}
```

The `pathToJson` variable may need adjustment to point to the contents of the Charybdis package. What I'm hoping to capture is the locale information you are using and which file(s) exhibit an issue when using the `readChar` function. For reference, here is the output of this code on my machine:

``` r
print(sessionInfo())
#> R version 4.1.0 (2021-05-18)
#> Platform: x86_64-w64-mingw32/x64 (64-bit)
#> Running under: Windows Server x64 (build 17763)
#> 
#> Matrix products: default
#> 
#> locale:
#> [1] LC_COLLATE=English_United States.1252 
#> [2] LC_CTYPE=English_United States.1252   
#> [3] LC_MONETARY=English_United States.1252
#> [4] LC_NUMERIC=C                          
#> [5] LC_TIME=English_United States.1252    
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> loaded via a namespace (and not attached):
#>  [1] digest_0.6.27     withr_2.4.2       magrittr_2.0.1    reprex_2.0.0     
#>  [5] evaluate_0.14     highr_0.9         stringi_1.7.3     rlang_0.4.11     
#>  [9] cli_3.0.1         rstudioapi_0.13   fs_1.5.0          rmarkdown_2.9    
#> [13] tools_4.1.0       stringr_1.4.0     glue_1.4.2        xfun_0.24        
#> [17] yaml_2.2.1        compiler_4.1.0    htmltools_0.5.1.1 knitr_1.33
pathToJson <- file.path(getwd(), "inst/cohorts/")
lfilesJson <-
  dir(
    path = pathToJson,
    pattern = "\\.json$",
    full.names = TRUE,
    recursive = TRUE
  )

for (file in lfilesJson)  {
  tryCatch({
    fileContents <- ""
    fileContents <- readChar(file, file.info(file)$size)
  },
  error = function(e) {
    print(paste0("Problem File: ", file))
  })
}
```

<sup>Created on 2021-07-28 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

Here you will see my session info and that my locale collation is LC_COLLATE=English_United States.1252. If there was an issue with reading the file via `readChar` then it would have appeared in the output. 

If you could post your results to this thread, I'm hoping it will help to isolate the problem. We encountered a similar problem due to special characters in a different study package as referenced in this commit: https://github.com/ohdsi-studies/Covid19VaccineAesiDiagnostics/commit/e0917506f41765d75c8db7577739333e4e4788be

**Comment by alabarga** [comment] 2021-07-28 16:21
in my case, the json files are at /usr/local/lib/R/site-library/Covid19CharacterizationCharybdis/cohorts/

Running you code I found problems with

[1] "Problem File: /usr/local/lib/R/site-library/Covid19CharacterizationCharybdis//cohorts//118.json"
[1] "Problem File: /usr/local/lib/R/site-library/Covid19CharacterizationCharybdis//cohorts//199.json"

sessionInfo()

```
R version 4.1.0 (2021-05-18)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux 10 (buster)

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.8.0
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.8.0

locale:
 [1] LC_CTYPE=C.UTF-8       LC_NUMERIC=C           LC_TIME=C.UTF-8
 [4] LC_COLLATE=C.UTF-8     LC_MONETARY=C.UTF-8    LC_MESSAGES=C.UTF-8
 [7] LC_PAPER=C.UTF-8       LC_NAME=C              LC_ADDRESS=C
[10] LC_TELEPHONE=C         LC_MEASUREMENT=C.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

loaded via a namespace (and not attached):
[1] compiler_4.1.0
```

**Comment by alabarga** [comment] 2021-07-28 16:24
a call to `file *` shows that all files are ASCII except these four

/usr/local/lib/R/site-library/Covid19CharacterizationCharybdis//cohorts//118.json: ISO-8859 text
/usr/local/lib/R/site-library/Covid19CharacterizationCharybdis//cohorts//143.json: ISO-8859 text
/usr/local/lib/R/site-library/Covid19CharacterizationCharybdis//cohorts//199.json: ISO-8859 text
/usr/local/lib/R/site-library/Covid19CharacterizationCharybdis//cohorts//200.json: ISO-8859 text

two of them are the problem ones

**Comment by alabarga** [comment] 2021-07-28 16:43
looks like problem with 118.json is the `ö` in `"Sjögren's syndrome"`  and 199.json `"Klumpke-Déjerine paralysis"`

**Comment by anthonysena** [comment] 2021-07-28 17:45
Thanks @alabarga - this is hugely helpful! I'll work to update the package.

**Closed as completed** 2021-07-28 18:00 UTC
